language: scala
services: docker
before_install:
  - docker run -d -p 127.0.0.1:8500:8500 consul:1.0.7 agent -dev -client 0.0.0.0 --enable-script-checks=true
scala:
  - 2.11.8
  - 2.12.0
jdk:
  - oraclejdk8
script:
  - sbt +test
