language: scala

services: docker

before_install:
  - docker run -d -p 127.0.0.1:8500:8500 consul:1.0.7 agent -dev -client 0.0.0.0 --enable-script-checks=true

scala:
  - 2.12.8

jdk:
  - oraclejdk8

script:
  - sbt clean coverage test coverageReport
  - sbt ";++ 2.11.11 test"

after_success:
  - bash <(curl -s https://codecov.io/bash)
